# Generated by Django 3.1.7 on 2021-03-24 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_albumimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumimage',
            name='created_at',
        ),
    ]
